### ISSUE TITLE
data-generator version not available 

### ISSUE THREAD

**Issue by tsahay2** [marmelab/react-admin-demo#2]
The data-generator version 2.4.0 is not available on npmjs. I can see the latest version is only 1.0.0 ( as can be seen [here](https://www.npmjs.com/package/data-generator). Hence, it is prompting an error while compiling.

**Comment by griiettner** [comment]
I'm having the same issue. I was looking to install the demo to see how things are under the hood and had no luck, because of this mismatch version. I believe it is not even the same package.

**Comment by fzaninotto** [comment]
data-generator is a **private** package. It's not published to npm at all, in any version.

```json
{
    "name": "data-generator",
    "version": "2.7.1",
    "private": true,
    ...
}
```

The data-generator package you're seing on npm isn't the same as the one we're using, and it was authored by someone else.

To install the demo, clone the react-admin repository and run `make install`.
