### ISSUE TITLE
Responsive doesn't work well for IE

### ISSUE THREAD

**Issue by guoyibj** [marmelab/react-admin-demo#4]
Bug: Comment doesn't word wrap for IE in mobile mode.
code: examples/demo/src/reviews/index.js

Snapshot in Chrome:
<img width="402" alt="chrome" src="https://user-images.githubusercontent.com/35130561/51651193-f28f3280-1fc5-11e9-83d6-1712a1b6492e.png">

Snapshot in IE:
![ie](https://user-images.githubusercontent.com/35130561/51651199-fae76d80-1fc5-11e9-9766-95544b88be63.png)

**Comment by fzaninotto** [comment]
Fixed in next by https://github.com/marmelab/react-admin/pull/2799
